# Write the actual Makefile.

import os


def makemakefile(outfp, makevars, files, target):
    outfp.write("# Makefile generated by freeze.py script\n\n")

    keys = sorted(makevars.keys())
    for key in keys:
        outfp.write(f"{key}={makevars[key]}\n")
    outfp.write(f"\nall: {target}\n\n")

    deps = []
    for i in range(len(files)):
        file = files[i]
        if file[-2:] == ".c":
            base = os.path.basename(file)
            dest = base[:-2] + ".o"
            outfp.write(f"{dest}: {file}\n")
            outfp.write(f"\t$(CC) $(PY_CFLAGS) $(PY_CPPFLAGS) -c {file}\n")
            files[i] = dest
            deps.append(dest)

    outfp.write("\n{}: {}\n".format(target, " ".join(deps)))
    outfp.write(
        "\t$(LINKCC) $(PY_LDFLAGS) $(LINKFORSHARED) {} -o {} $(LDLAST)\n".format(
            " ".join(files), target
        )
    )

    outfp.write(f"\nclean:\n\t-rm -f *.o {target}\n")
